### ISSUE TITLE
GET on /v1/reboot is a thing apparently

### ISSUE THREAD

**Issue by brysonthor** [CWSpear/everlights#1]
I was reading your code to try and find a way to reboot my box with a cron job, (it has issues turning on programs on a schedule) and I took a shot in the dark and it looks like if you do a GET to /v1/reboot it reboots the v3 controller... I would do a PR but I'm too lazy... Maybe I will at some point...

**Comment by CWSpear** [comment]
Added reboot method to the SDK and published `everlights@1.0.0-beta.0`.

See: https://github.com/CWSpear/everlights/commit/e66b7c01b9d92fcc5ed6fdb41ca77d2b51a33317#diff-8c0e2d1236b3f9b5cc2f09972bf07776c88c5012a6cc7759988abddc2d3f33aaR195
